#!/usr/bin/env php
<?php

date_default_timezone_set('UTC');

function dd($data) { var_dump($data); die(); }

require('vendor/autoload.php');

$config['cloud_storage'] = require('app/config/production/cloud_storage.php');

if ( ! class_exists('Imagick'))
{
	throw new Exception('PHP Imagick extension not installed.');
}

(new \SssPhotoLibrary\Console\Application)->run();
